# Default values for minio-operator.

operator:
  clusterDomain: "${cluster_domain}"
  nsToWatch: "${ns_to_watch}"
  image:
    repository: minio/operator
    tag: ${tag}
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

console:
  image:
    repository: minio/console
    tag: v0.7.4
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}

## MinIO Tenant Definition
tenants:
  # Tenant name
  - name: ${tenant_name}
    namespace: ${ns_to_watch}
    ## Registry location and Tag to download MinIO Server image
    image:
      repository: minio/minio
      tag: ${tenants_image_tag}
      pullPolicy: IfNotPresent
    imagePullSecrets: []
    ## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
    ## If not specified, the Tenant pods will be dispatched by default scheduler.
    scheduler: {}
    ## Specification for MinIO Pool(s) in this Tenant.
    pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 1
        ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 4
        ## size specifies the capacity per volume
        size: 10Gi
        ## storageClass specifies the storage class name to be used for this pool
        storageClassName: ${storage_class}
        ## Used to specify a toleration for a pod
        tolerations: {}
        ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
        ## eligible to run on a node, the node must have each of the
        ## indicated key-value pairs as labels.
        ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
        nodeSelector: {}
        ## Affinity settings for MinIO pods. Read more about affinity
        ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
        affinity: {}
        ## Configure resource requests and limits for MinIO containers
        resources: {}
        ## Configure security context
        securityContext: {}
    ## Mount path where PV will be mounted inside container(s).
    mountPath: /export
    ## Sub path inside Mount path where MinIO stores data.
    subPath: /data
    # pool secrets
    secrets:
      enabled: true
      name: ${tenant_name}-secret
      accessKey: minio
      secretKey: minio123
    # pool metrics to be read by Prometheus
    metrics:
      enabled: false
      port: 9000
    certificate:
      ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
      ## TLS for MinIO Tenant pods. Create secrets as explained here:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCertSecret: {}
#        - name: ${minio-tls-cert-name}
#          type: kubernetes.io/tls
      ## Enable automatic Kubernetes based certificate generation and signing as explained in
      ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
      requestAutoCert: true
      ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
      ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
      ## not provided. DNS name format is *.minio.default.svc.cluster.local
      certConfig: {}
#        commonName: "*.minio.${ns_to_watch}.svc.cluster.local"
#        organizationName:
#          - "Farhand Inc"
#        dnsNames:
#          - '*.minio.${ns_to_watch}.svc.cluster.local'
#          - '${tenant_name}-hl-svc.${ns_to_watch}.svc.cluster.local'
#          - '${tenant_name}-hl-svc'
    ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
    ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
    s3:
      ## This feature is turned off by default
      bucketDNS: true
    ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
    ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
    ## for details.
    podManagementPolicy: Parallel
    ## serviceMetadata allows passing additional labels and annotations to MinIO and Console specific
    ## services created by the operator.
    serviceMetadata: {}
    ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
    env: {}
    ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
    ## This is applied to MinIO pods only.
    ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
    priorityClassName : ""
    ## Define configuration for Console (Graphical user interface for MinIO)
    ## Refer https://github.com/minio/console
    console:
      image:
        repository: minio/console
        tag: v0.7.4
        pullPolicy: IfNotPresent
      replicaCount: 1
      secrets:
        enabled: true
        name: ${tenant_name}-console-secret
        passphrase: SECRET
        salt: SECRET
        accessKey: YOURCONSOLEACCESS
        secretKey: YOURCONSOLESECRET
